language: ruby
rvm:
  - 2.4.1
before_install:
  - gem install bundler:2.0.1
  - gem update --system
  - gem install bundler
  - bundle update --bundler
before_script:
  - chmod +x ./script/cibuild
script: ./script/cibuild
gemfile: gemfiles/Gemfile.ci
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"
  - add-travis
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false # route your build to the container-based infrastructure for a faster build
cache: bundler
notifications:
  email: true
